{{- $name := include "newrelic-tag-deployment.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "newrelic-tag-deployment.labels" . | nindent 4 }}
